### ISSUE TITLE
Not running on a mac, libtiff missing

### ISSUE THREAD

**Issue by rantahar** [sa2c/CellProfiler-RunOnCluster#13]
Jeffs-iMac:~ JeffSDavies$ cat /tmp/cellprofiler_
cellprofiler_error   cellprofiler_output  
Jeffs-iMac:~ JeffSDavies$ cat /tmp/cellprofiler_output 
/Users/JeffDavies/Desktop/CellProfiler.app/Contents/MacOS/../Resources/lib/python2.7/:/Users/JeffDavies/Desktop/CellProfiler.app/Contents/MacOS/../Resources/lib/python2.7//lib-dynload:/var/folders/vr/6dz49cg93jd539mxkk4pbv200000gp/T/tmp.c7QwoE3l
Jeffs-iMac:~ JeffSDavies$ cat /tmp/cellprofiler_error 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/Users/JeffDavies/Desktop/CellProfiler.app/Contents/MacOS/../Resources/CellProfiler.py", line 10, in <module>
    cellprofiler.__main__.main()
  File "/Users/JeffDavies/Desktop/CellProfiler.app/Contents/Resources/cellprofiler/__main__.py", line 138, in main
    import cellprofiler.gui.app
  File "/Users/JeffDavies/Desktop/CellProfiler.app/Contents/Resources/cellprofiler/gui/app.py", line 12, in <module>
    import wx
  File "wx/__init__.pyc", line 45, in <module>
  File "wx/_core.pyc", line 4, in <module>
  File "wx/_core_.pyc", line 14, in <module>
  File "wx/_core_.pyc", line 10, in __load
ImportError: dlopen(/Users/JeffDavies/Desktop/CellProfiler.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /Users/JeffDavies/Desktop/CellProfiler.app/Contents/Frameworks/libtiff.5.dylib
  Reason: image not found
Jeffs-iMac:~ JeffSDavies$

**Comment by rantahar** [comment]
Need to test on a virtual mac with clean install. Pushing to beta 2.
